version: '3.8'

services:
  message-cleaner-bot:
    build: .
    env_file: .env
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    command: ["node", "bot.js"]
    working_dir: /usr/src/app
